Add ATMega88P/PA support.  Improve makeall.

diff --git a/optiboot/bootloaders/optiboot/makeall b/optiboot/bootloaders/optiboot/makeall
--- a/optiboot/bootloaders/optiboot/makeall
+++ b/optiboot/bootloaders/optiboot/makeall
@@ -1,6 +1,39 @@
 #!/bin/bash
 make clean
-#
+
+if [ -z "$AVR_FREQ" ]
+then
+  AVR_FREQ=8000000L
+fi
+
+if [ -z "$BAUD_RATE" ]
+then
+  BAUD_RATE=57600
+fi
+
+export AVR_FREQ
+export BAUD_RATE
+
+for chip in $(cat Makefile.generic | grep -oP "^([A-Za-z0-9_]+)(?:\:)" | grep -v isp | sort | uniq | sed s/://)
+do
+  echo -n "Building $chip with CPU $AVR_FREQ and $BAUD_RATE BAUD ... "
+  
+  if ! ( make $chip 2>&1 ) >$chip.build_log
+  then
+    echo "FAILED, SEE: $chip.build_log"
+    exit
+  else
+    echo -n "OK, SIZE: "
+    avr-size optiboot_${chip}_${AVR_FREQ}_${BAUD_RATE}.hex | grep -oP "[1-9][0-9]+" | head -1
+  fi
+done
+
+ls *hex
+
+exit
+
+
+
 #  buildable platforms of somewhat questionable support level
 make lilypad
 make pro8
@@ -14,17 +47,6 @@ make diecimila
 make bobuino
 make wildfirev2
 make atmega1284
-make atmega32
-make atmega88
-make atmega168p
-
-#
-# The "big three" standard bootloaders.
-# These need to be built AFTER the platforms, or they'll get renamed
-make atmega8
-make atmega168
-make atmega328
-
 #
 # Atmel development board targets
 make xplained168pb
